---
title: "R codes "
author: "Leonard Maaya, Martina Vandebroek"
date: "2023-07-15"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```


```{r packages, echo=FALSE, warning=FALSE, message=FALSE}

rm(list = ls())

library(tidyverse)
library(flextable)
library(officer)
library(data.table)

std_border = fp_border(color="gray")
std_borderFoot = fp_border(color="black", width = 2)
format_fn = function(x, d) formatC(x, format = 'f', digits = 2)

```


# PART 1

## Population and sample regression lines

```{r regressionLines, warning=FALSE, message=FALSE, eval = TRUE}

# settings

samplesize = 20
beta = c(5, 2)
xrange = c(0, 10)
errorstdev = 7

set.seed(1072023)

# end of settings

## population + sample data and regression lines

step = (xrange[2] - xrange[1])/(samplesize - 1)
midrange = beta[1] + beta[2]*2*(xrange[2] - xrange[1])/2
xvalues = seq(xrange[1], xrange[2], step)
y = beta[1] + beta[2]*xvalues

df = cbind(xvalues = seq(xrange[1], xrange[2], step)) %>% as.data.frame() %>%
  mutate(y = beta[1] + beta[2]*xvalues, epsilon = rnorm(samplesize, 0, errorstdev)) %>%
  mutate(yvalues = y + epsilon) %>% 
  pivot_longer(cols = contains('y'), names_to = 'ytype', values_to = 'yvalues') %>%
  mutate(ytype = factor(ifelse(ytype == 'yvalues', 'sample', 'population'))) %>% 
  select(-c(epsilon))


lm_fit = lm(yvalues ~ xvalues, data=df %>% filter(ytype=='sample')) # for predicted values

## plot

ggplot(df, aes(x= xvalues, y = yvalues, col = ytype)) + 
  geom_point(shape = 16, size = 2, stat = "identity") + theme_bw() + 
  labs(y = "y", x = 'x') + ggtitle('Population and sample regression lines') + 
  ggeasy::easy_center_title() + scale_colour_manual(values= c('red', 'blue')) +
  scale_x_continuous(breaks = seq(0, 10, 2), limits = c(0, 10), labels = seq(0, 10, 2)) + 
  scale_y_continuous(breaks = c(seq(0, 30, 5)), limits = c(0, 30)) +
  geom_line(data = df %>% filter(ytype=='population'), aes(x = xvalues, y = yvalues),
            color="red", linewidth = 1) +
  geom_line(data = broom::augment(lm_fit), aes(x = xvalues, y = predict(lm_fit)),
            color="blue", linewidth = 1) + guides(col = guide_legend("Y-values"))


```

## Intercept & slope histograms

```{r intslopeshistograms, warning=FALSE, message=FALSE, eval = TRUE}


# settings

samplesize = 10
beta = c(5, 2)
xrange = c(0, 10)
errorstdev = 7
nrsim = 100

# set.seed(1072023)

# end of settings

## population + sample data and regression lines

step = (xrange[2] - xrange[1])/(samplesize - 1)
midrange = beta[1] + beta[2]*2*(xrange[2] - xrange[1])/2
xvalues = seq(xrange[1], xrange[2], step)

# function that generates several samples and computes performs regression: outputs
#  intercept & slope


intslop_fn = function(){
  
  df = cbind(xvalues = seq(xrange[1], xrange[2], step)) %>% as.data.frame() %>%
    mutate(epsilon = rnorm(samplesize, 0, errorstdev)) %>% 
    mutate(yvalues = beta[1] + beta[2]*xvalues + epsilon) %>% select(-c(epsilon))
  
  fit = lm(yvalues ~ xvalues, data = df)
  
  return(fit$coefficients)
}

df = cbind(r = 1:nrsim) %>% as.data.frame()
df_intslopes = df %>% group_by(`r`) %>% nest() %>%
  mutate(model = map(data, ~ intslop_fn())) %>% unnest(model) %>% 
  mutate("values" = unname(model)) %>% select(-c(data, model)) %>%
  mutate(parameter = as.factor(ifelse(row_number() == 1, 'intercepts', 'slopes'))) %>% 
  ungroup() 
  
data_vline <- data.frame(parameter = unique(df_intslopes$parameter),  # Create data for lines
                         vline = c(beta[1], beta[2]))

## histograms

ggplot(df_intslopes, aes(x= values)) + theme_bw() +  
  geom_histogram(bins = 15, color = "black", fill = "gray")  + 
  facet_grid(~ parameter, scales = "free", labeller = label_wrap_gen(multi_line = TRUE)) +
    geom_vline(data = data_vline, aes(xintercept = vline), lwd = 1)



# scatter plot
## long -> wide
df_intslopesWide = df_intslopes %>% 
  pivot_wider(names_from = 'parameter', values_from = 'values')


ggplot(df_intslopesWide, aes(x= intercepts, y = slopes)) + 
  geom_point(shape = 16, size = 2, stat = "identity") + theme_bw() + 
  ggtitle('Correlation plot') + ggeasy::easy_center_title() +
  scale_x_continuous(breaks = seq(-7.5, 20, 5), limits = c(-7.5, 20), labels = seq(-7.5, 20, 5)) + 
  scale_y_continuous(breaks = c(seq(0, 4.5, 1)), limits = c(0, 4.5))

```


# Sports data

## Leicester's incredible run in 2015/16

* <https://statsbomb.com/news/the-2015-16-big-5-leagues-free-data-release-premier-league/>
  * <https://github.com/statsbomb/StatsBombR>
  * Instructions on working with StatsBombR can be found on this link: 
      * <https://statsbomb.com/wp-content/uploads/2022/08/Working-with-R.pdf>
      * followed this installation instruction in Base R
          * <https://github.com/statsbomb/StatsBombR>
  * Installing RTools
      * <https://www.youtube.com/watch?v=hBTObNFFkhs>

```{r sportsdata, echo=FALSE, warning=FALSE, message=FALSE}

# followed this instructions (available at: https://github.com/statsbomb/StatsBombR) after installing Rtools + in Base R
# 
# install.packages("devtools")
# devtools::install_github("statsbomb/SDMTools")
# devtools::install_github("statsbomb/StatsBombR")

library(StatsBombR)

Comp = FreeCompetitions() %>% 
  filter(country_name == 'England' & competition_name == 'Premier League' &
           competition_gender == 'male' & season_name == '2015/2016')
Matches = FreeMatches(Comp)
StatsBombData <- free_allevents(MatchesDF = Matches, Parallel = T)
StatsBombData = allclean(StatsBombData) 


# Goals and shots

## Totals
shots_goals = StatsBombData %>% group_by(team.name) %>% 
  summarise(shots = sum(type.name=="Shot", na.rm = TRUE),
            goals = sum(shot.outcome.name=="Goal", na.rm = TRUE))

## per game

shots_goals_pg = StatsBombData %>%
group_by(team.name) %>%
  summarise(shots = sum(type.name=="Shot", na.rm = TRUE)/n_distinct(match_id),
            goals = sum(shot.outcome.name=="Goal", na.rm = TRUE)/n_distinct(match_id))

```


## Shots and goals per team


```{r shotsandgoalsTable, echo=FALSE, warning=FALSE, message=FALSE}

shots_goalsFormatted = shots_goals %>% rename("Team" = `team.name`) %>%
  mutate_if(is.numeric, .funs = format_fn) 

flextable(shots_goalsFormatted) %>% hline(part="body", border = std_border) %>% 
  hline_bottom(part="body", border = std_borderFoot) %>% 
  hline_top(part="body", border = std_borderFoot) %>% 
  set_caption(caption ="Goals and shots per team in 2015/16 season.") %>%  merge_h(part = "header") %>%
  merge_v(part = "header") %>%  width(j = c(1:3), width = c(1.5, 1, 1)) %>% vline(border = std_border, part = "all") %>% 
  align(align = "center", part = "all") %>% align(align = "left", part = "all", j = 1) %>% fix_border_issues(part = "all") %>% 
  hline_top(part="header", border = std_borderFoot) %>% fontsize(size = 10, part = "all")

```



```{r plotshotspergame, warning = FALSE, echo=FALSE, message=FALSE}
# Plot the data

ggplot(data = shots_goals, aes(x = reorder(team.name, shots), y = shots)) +
  geom_bar(stat = "identity", width = 0.5) + labs(y="Shots") + 
  theme(axis.title.y = element_blank()) + scale_y_continuous( expand = c(0,0)) + 
  coord_flip() + theme_SB() 


```


## Top 10 players by shots (2015/16)

```{r playershotsper90, warning=FALSE, echo=FALSE, message=FALSE}

player_shots = StatsBombData %>% group_by(player.name, player.id) %>%
  summarise(shots = sum(type.name=="Shot", na.rm = TRUE)) 

player_minutes = get.minutesplayed(StatsBombData) 
player_minutes = player_minutes %>% group_by(player.id) %>% 
  summarise(minutes = sum(MinutesPlayed)) 

player_shots = left_join(player_shots, player_minutes) 
player_shots = player_shots %>% mutate(nineties = minutes/90) 
player_shots = player_shots %>% mutate(shots_per90 = shots/nineties) 

cols = colnames(player_shots)[-(1:2)]

player_shotsT10 = player_shots %>% as.data.table() %>% .[order(-shots_per90)] %>% 
  .[1:10, ] %>% mutate_at(.vars = all_of(cols), .funs = format_fn) %>% as.data.frame()

flextable(player_shotsT10) %>% hline(part="body", border = std_border) %>% 
  hline_bottom(part="body", border = std_borderFoot) %>% 
  hline_top(part="body", border = std_borderFoot) %>% 
  set_caption(caption ="Top 10 players by shots in 2015/16 season.") %>%  merge_h(part = "header") %>%
  merge_v(part = "header") %>%  width(j = c(1), width = c(2.1)) %>% vline(border = std_border, part = "all") %>% 
  align(align = "center", part = "all") %>% align(align = "left", part = "all", j = 1) %>% fix_border_issues(part = "all") %>% 
  hline_top(part="header", border = std_borderFoot) %>% fontsize(size = 10, part = "all")

```


## Plotting passes

```{r passesplot, warning=FALSE, echo=FALSE, message=FALSE}

library(SBpitch)

passes = StatsBombData %>% filter(type.name=="Pass" & is.na(pass.outcome.name) & 
                              player.name %like% "Golo") %>% 
  filter(pass.end_location.x>=102 & pass.end_location.y<=62 & pass.end_location.y>=18)

create_Pitch() +
 geom_segment(data = passes, aes(x = location.x, y = location.y,
 xend = pass.end_location.x, yend = pass.end_location.y),
 lineend = "round", size = 0.5, colour = "#000000", arrow =
arrow(length = unit(0.07, "inches"), ends = "last", type = "open")) + 
 labs(title = "N'Golo Kante, Completed Box Passes", subtitle = "N'Golo Kante, 2015-16") + 
  scale_y_reverse() + coord_fixed(ratio = 105/100) 

```


# Construction dataset

* <https://archive.ics.uci.edu/>